#!/bin/env -S "bash"

set -o xtrace 

# make a copy of the current initialization script available to the container
cp to_image/touchup*.sh .
chmod a+x to_image/touchup*.sh

# get inital image fiile and mount for nspawn
xz --decompress --stdout 2022-04-04-raspios-bullseye-arm64-lite.img.xz > a.img

# extend the root filesystem -- later steps will overflow 2G

truncate --size=+2G a.img
# resize 2nd partition (/root)
echo ", +" | sudo sfdisk -N 2 a.img

# attach the loop device
loopfile=$(sudo losetup -Pf --show a.img)

# clean up /root, then extend it to fill

sudo e2fsck -pD -f ${loopfile}p2
sudo resize2fs ${loopfile}p2


sudo mount ${loopfile}p2 /media/bobhy/rootfs
sudo mount ${loopfile}p1 /media/bobhy/rootfs/boot


# and run it.
sudo systemd-nspawn \
    -D /media/bobhy/rootfs \
    --bind-ro=/:/pibuild/fromhost \
    --bind=$PWD/from_image/:/pibuild/tohost \
    --bind=$PWD/to_image/:/pibuild/fromsrc \
    --as-pid2 --pipe \
/usr/bin/bash <<EOF
passwd root
simple
simple
passwd -u root
echo skserv > /etc/hostname
EOF

# don't know how to run touchup from a script!
# for now, log into root and run it manually.
sudo systemd-nspawn --machine=aimage \
    -D /media/bobhy/rootfs \
    --bind-ro=/:/pibuild/fromhost \
    --bind=$PWD/from_image/:/pibuild/tohost \
    --bind=$PWD/to_image/:/pibuild/fromsrc \
    --boot 
    
##sleep 3
##sudo systemd-run -M a_image <<EOF
##root
##simple
##bash -x /pibuild/fromsrc/touchup.sh
##EOF

##sudo umount ${loopfile}p*

##sudo losetup -d $loopfile

# the other thing we don't know yet
# is how to burn the image to a SD card
# and pick up some magic that rpi imager is doing
# again, for now, just use rpi manually.